const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const API_BASE=(location.hostname.endsWith('github.io')||location.hostname==='localhost')?(localStorage.getItem('rioApiBase')||'https://rio-ai-studio.vercel.app'):'';
const API=p=>`${API_BASE}${p}`;
const templates=[['إعلان منتج','business','PRODUCT','9:16'],['إعلان سوشيال','social','SOCIAL','9:16'],['فلوق سفر','travel','TRAVEL','16:9'],['مطاعم ومأكولات','food','FOOD','1:1'],['إطلاق منتج','business','LAUNCH','9:16'],['قصة قصيرة','social','STORY','9:16']];
let projects=JSON.parse(localStorage.getItem('rioProjectsV07')||'[]');
let credits=Number(localStorage.getItem('rioCreditsV07')||120);
let material={file:null,text:''};
let state={media:null,audio:null,mediaType:null,mediaUrl:null,audioUrl:null,filter:'none',ratio:'9/16',text:'',projectId:null,history:[],i2vFile:null};
const DB='rioStudioDBv07',STORE='files';
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2600)}
function saveMeta(){localStorage.setItem('rioProjectsV07',JSON.stringify(projects));localStorage.setItem('rioCreditsV07',String(credits));$('#creditCount').textContent=credits;$('#accountCredits').textContent=credits;$('#usageBar').style.width=Math.max(5,Math.min(100,credits/1.2))+'%'}
function spend(n=1){if(credits<n){toast('رصيد AI غير كافٍ');return false}credits-=n;saveMeta();return true}
function showScreen(n){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+n)?.classList.add('active');$$('.side,.nav').forEach(x=>x.classList.toggle('active',x.dataset.screen===n));window.scrollTo(0,0)}
function openEditor(){ $('#editor').setAttribute('aria-hidden','false'); document.body.classList.add('editor-open'); initEditor(); }
function closeEditor(){ $('#editor').setAttribute('aria-hidden','true'); document.body.classList.remove('editor-open'); }
function modal(h){$('#modalBody').innerHTML=h;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function putFile(id,blob){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(blob,id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function getFile(id){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function newProject(name,meta,tag){return {id:crypto.randomUUID(),name,meta,tag,createdAt:Date.now()}}
function renderProjects(){
 const rows=projects.slice().sort((a,b)=>b.createdAt-a.createdAt);
 $('#recent').innerHTML=rows.slice(0,4).map(p=>`<button class="recent" data-project="${p.id}"><div class="thumb">${esc(p.tag||'RIO')}</div><b>${esc(p.name)}</b><small>${esc(p.meta||'مشروع')}</small></button>`).join('')||'<div class="recent"><div class="thumb">RIO</div><b>لا توجد مشاريع</b><small>ابدأ من أداة في الصفحة الرئيسية.</small></div>';
 $('#projectList').innerHTML=rows.map(p=>`<button class="project-row" data-project="${p.id}"><div class="mini">${esc(p.tag||'RIO')}</div><div><b>${esc(p.name)}</b><small>${esc(p.meta||'مشروع')}</small></div><span>›</span></button>`).join('')||'<div class="project-row"><div><b>لا توجد مشاريع بعد</b><small>ستظهر هنا نتائج AI والمشاريع المحفوظة.</small></div></div>';
}
function renderTemplates(cat='all'){ $('#templatesGrid').innerHTML=templates.filter(t=>cat==='all'||t[1]===cat).map(t=>`<button class="template" data-template="${esc(t[0])}"><div class="thumb">${t[2]}</div><b>${esc(t[0])}</b><small>قالب · ${t[3]}</small></button>`).join('') }
function plans(){modal(`<h2>خطط ريو</h2><p>هذه الصفحة تعرض هيكل الخطط فقط. لا يوجد زر شراء وهمي في هذه النسخة؛ الدفع الحقيقي يحتاج ربط مزود دفع/نجوم تيليجرام.</p><div class="settings-list"><div class="project-row"><div><b>Starter</b><small>500 رصيد AI</small></div><strong>19 ر.س</strong></div><div class="project-row"><div><b>Creator</b><small>2,000 رصيد AI</small></div><strong>49 ر.س</strong></div><div class="project-row"><div><b>Pro</b><small>5,000 رصيد AI</small></div><strong>99 ر.س</strong></div><div class="project-row"><div><b>Studio</b><small>15,000 رصيد AI</small></div><strong>249 ر.س</strong></div></div>`)}
async function checkAPI(){try{const r=await fetch(API('/api/health'));const d=await r.json();modal(`<h2>حالة الاتصال</h2><div class="result-card"><div class="result-text">${esc(JSON.stringify(d,null,2))}</div></div>`)}catch(e){modal(`<h2>فشل الاتصال</h2><p>${esc(e.message)}</p>`)} }
function settings(){modal(`<h2>الإعدادات</h2><div class="settings-list"><button class="tool-choice" id="healthBtn">اختبار اتصال Backend</button><button class="tool-choice" id="apiBaseBtn">تغيير عنوان API</button><button class="tool-choice" id="clearBtn">مسح المشاريع المحلية</button></div>`);$('#healthBtn').onclick=checkAPI;$('#apiBaseBtn').onclick=()=>{const v=prompt('عنوان Vercel API بدون / في النهاية',API_BASE);if(v!==null){localStorage.setItem('rioApiBase',v.replace(/\/$/,''));toast('تم حفظ عنوان API');}};$('#clearBtn').onclick=()=>{projects=[];saveMeta();renderProjects();closeModal();toast('تم مسح المشاريع المحلية')};}
function help(){modal('<h2>مركز المساعدة</h2><p>Rio V0.7 يضع مفتاح FAL_KEY على Vercel فقط. عمليات الفيديو والصور والصوت والنص ترسل إلى Backend ثم تعود النتيجة إلى التطبيق. المشاريع المحلية تحفظ على جهازك.</p>')}
function bindChoice(){ $$('[data-choice]').forEach(b=>b.onclick=()=>{$$(`[data-choice="${b.dataset.choice}"]`).forEach(x=>x.classList.remove('active'));b.classList.add('active')}) }
function dataURL(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(file)})}
async function aiModal(type){
 const title={image:'إنشاء صورة AI','image-video':'صورة → فيديو','text-video':'فيديو AI',tts:'تعليق صوتي AI',stt:'تفريغ صوت'}[type]||'AI';
 if(!spend(type==='text-video'||type==='image-video'?10:type==='image'?3:1))return;
 if(type==='stt'){
  modal(`<h2>${title}</h2><p>اختر ملف صوت قصير. الحد العملي للنسخة الحالية 4MB عند الإرسال كـData URI.</p><input id="sttFile" type="file" accept="audio/*" class="file-input"><div class="field"><label>لغة اختيارية</label><input id="sttLang" class="prompt" style="min-height:50px" placeholder="ar أو en"></div><button class="modal-action" id="aiSubmit">تفريغ الصوت</button><div id="aiStatus"></div>`);$('#aiSubmit').onclick=()=>runAI('stt');return;
 }
 const isImg=type==='image',isI2V=type==='image-video',isTts=type==='tts';
 const promptLabel=isTts?'النص الذي تريد تحويله إلى صوت…':'صف النتيجة بالتفصيل…';
 modal(`<h2>${title}</h2>${isI2V?'<button class="outline" id="pickI2V">＋ اختيار صورة</button><input id="i2vInput" type="file" accept="image/*" hidden>':''}<textarea id="aiPrompt" class="prompt" placeholder="${promptLabel}"></textarea><div class="field"><label>المقاس</label><div class="selects"><button class="select active" data-choice="ratio" data-value="9:16">9:16</button><button class="select" data-choice="ratio" data-value="16:9">16:9</button><button class="select" data-choice="ratio" data-value="1:1">1:1</button></div></div>${isTts?'<div class="field"><label>الصوت</label><div class="selects"><button class="select active" data-choice="voice" data-value="Rachel">Rachel</button><button class="select" data-choice="voice" data-value="Aria">Aria</button><button class="select" data-choice="voice" data-value="Charlotte">Charlotte</button></div></div>':''}${isImg||isTts?'':'<div class="field"><label>الجودة</label><div class="selects"><button class="select active" data-choice="res" data-value="720p">720p</button><button class="select" data-choice="res" data-value="1080p">1080p</button></div></div>'}<button class="modal-action" id="aiSubmit">${isImg?'إنشاء الصورة':isI2V?'إنشاء الفيديو من الصورة':isTts?'إنشاء الصوت':'إنشاء الفيديو'}</button><div id="aiStatus"></div>`);
 bindChoice();
 if(isI2V){$('#pickI2V').onclick=()=>$('#i2vInput').click();$('#i2vInput').onchange=e=>{state.i2vFile=e.target.files[0]||null;$('#pickI2V').textContent=state.i2vFile?'تم اختيار الصورة ✓':'＋ اختيار صورة'}}
 $('#aiSubmit').onclick=()=>runAI(type);
}
async function runAI(type){
 const btn=$('#aiSubmit'),status=$('#aiStatus');btn.disabled=true;status.textContent='جاري إرسال الطلب…';
 try{
  const body={type};
  if(type==='stt'){
   const f=$('#sttFile').files[0];if(!f)throw Error('اختر ملف صوت أولاً');if(f.size>4*1024*1024)throw Error('الملف أكبر من 4MB في هذه النسخة.');body.audioData=await dataURL(f);body.languageCode=$('#sttLang').value.trim()||undefined;
  }else if(type==='tts'){body.text=$('#aiPrompt').value.trim();body.languageCode='ar';body.voice=$('[data-choice="voice"].active')?.dataset.value||'Rachel';if(!body.text)throw Error('اكتب النص أولاً')
  }else{body.prompt=$('#aiPrompt').value.trim();body.aspectRatio=(($('[data-choice="ratio"].active')?.dataset.value||'9:16')==='1:1'?'9:16':($('[data-choice="ratio"].active')?.dataset.value||'9:16'));body.resolution=$('[data-choice="res"].active')?.dataset.value||'720p';body.duration='8s';body.generateAudio=true;if(!body.prompt)throw Error('اكتب الوصف أولاً');if(type==='image-video'){if(!state.i2vFile)throw Error('اختر صورة أولاً');body.imageData=await dataURL(state.i2vFile)}}
  const r=await fetch(API('/api/ai'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const raw=await r.text();let d;try{d=JSON.parse(raw)}catch{throw Error(`Backend أعاد HTML بدل JSON. تأكد من نشر Vercel: ${raw.slice(0,80)}`)}if(!r.ok)throw Error(d.error||'فشل الطلب');status.textContent='تم الإرسال ✓ جاري التوليد…';await poll(d);
 }catch(e){btn.disabled=false;status.textContent=e.message}
}
async function poll(job){for(let i=0;i<100;i++){await new Promise(r=>setTimeout(r,3000));const r=await fetch(API(`/api/status?requestId=${encodeURIComponent(job.requestId)}&model=${encodeURIComponent(job.model)}&type=${encodeURIComponent(job.type)}`));const raw=await r.text();let d;try{d=JSON.parse(raw)}catch{throw Error('Backend أعاد استجابة غير صالحة أثناء متابعة النتيجة')}if(!r.ok)throw Error(d.error||'فشل فحص الحالة');if(d.status==='COMPLETED'){return finishAI(job.type,d)}if(['FAILED','ERROR','CANCELLED'].includes(d.status))throw Error(d.error||'فشل محرك AI');$('#aiStatus').textContent=`قيد التنفيذ… ${Math.min(99,Math.round(i))}%`}throw Error('التوليد ما زال مستمرًا. افتح المشاريع لاحقًا إذا طال الانتظار.')}
async function finishAI(type,d){
 const p=await makeResultProject(type,d);renderProjects();
 if(type==='image')showResult('تم إنشاء الصورة',`<img src="${esc(d.imageUrl)}" alt="نتيجة AI"><a class="white-btn" href="${esc(d.imageUrl)}" target="_blank" rel="noopener">فتح الصورة</a>`);
 else if(type==='text-video'||type==='image-video')showResult('تم إنشاء الفيديو',`<video src="${esc(d.videoUrl)}" controls playsinline></video><a class="white-btn" href="${esc(d.videoUrl)}" target="_blank" rel="noopener">فتح الفيديو</a>`);
 else if(type==='tts')showResult('تم إنشاء الصوت',`<audio src="${esc(d.audioUrl)}" controls></audio><a class="white-btn" href="${esc(d.audioUrl)}" target="_blank" rel="noopener">فتح الصوت</a>`);
 else if(type==='stt')showResult('تم تفريغ الصوت',`<div class="result-text">${esc(d.text)}</div><button class="white-btn" id="copyResult">نسخ النص</button>`);
 $('#copyResult')?.addEventListener('click',()=>navigator.clipboard?.writeText(d.text).then(()=>toast('تم النسخ')));
}
async function makeResultProject(type,d){const p=await newProject(type==='image'?'صورة AI':type==='tts'?'تعليق صوتي':type==='stt'?'تفريغ صوت':'فيديو AI','نتيجة AI · '+type.toUpperCase(),type.toUpperCase());p.remoteUrl=d.imageUrl||d.videoUrl||d.audioUrl||null;p.text=d.text||null;projects.unshift(p);saveMeta();return p}
function showResult(title,body){modal(`<h2>${title}</h2><div class="result-card">${body}</div>`)}
function writer(){if(!spend(1))return;modal(`<h2>الكتابة والمحتوى</h2><textarea id="writerPrompt" class="prompt" placeholder="مثال: اكتب حملة إعلانية لقهوة سعودية فاخرة من 3 منشورات مع عناوين وCTA"></textarea><button class="modal-action" id="writerGo">إنشاء المحتوى فعليًا</button><div id="writerStatus"></div>`);$('#writerGo').onclick=async()=>{const q=$('#writerPrompt').value.trim();if(!q)return toast('اكتب المطلوب');$('#writerStatus').textContent='جاري الكتابة…';await textAI(q,'writer',$('#writerStatus'))}}
function translate(){if(!spend(1))return;modal(`<h2>الترجمة AI</h2><textarea id="trIn" class="prompt" placeholder="ضع النص هنا"></textarea><div class="selects" style="margin-top:10px"><button class="select active" data-choice="target" data-value="English">English</button><button class="select" data-choice="target" data-value="العربية">العربية</button><button class="select" data-choice="target" data-value="Français">Français</button></div><button class="modal-action" id="trGo">ترجمة فعليًا</button><div id="trOut"></div>`);bindChoice();$('#trGo').onclick=async()=>{const q=$('#trIn').value.trim(),lang=$('[data-choice="target"].active')?.dataset.value||'English';if(!q)return toast('ضع النص أولاً');await textAI(`ترجم النص التالي إلى ${lang}. حافظ على المعنى والنبرة ولا تضف شرحًا.\n\n${q}`,'translation',$('#trOut'))}}
async function textAI(prompt,kind,outEl){outEl.textContent='جاري التنفيذ…';try{const r=await fetch(API('/api/ai'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'text',prompt,systemPrompt:kind==='translation'?'أنت مترجم محترف.':'أنت كاتب محتوى وتسويق محترف.'})});const d=await r.json();if(!r.ok)throw Error(d.error||'فشل إرسال النص');const result=await pollText(d);outEl.innerHTML=`<div class="result-card"><div class="result-text">${esc(result)}</div><button class="white-btn" id="copyText">نسخ</button></div>`;$('#copyText').onclick=()=>navigator.clipboard?.writeText(result).then(()=>toast('تم النسخ'))}catch(e){outEl.textContent=e.message}}
async function pollText(job){for(let i=0;i<80;i++){await new Promise(r=>setTimeout(r,2500));const r=await fetch(API(`/api/status?requestId=${encodeURIComponent(job.requestId)}&model=${encodeURIComponent(job.model)}&type=text`));const d=await r.json();if(d.status==='COMPLETED'){const p=await newProject('نص AI','كتابة · LLM','TEXT');p.text=d.text;projects.unshift(p);saveMeta();renderProjects();return d.text}if(['FAILED','ERROR','CANCELLED'].includes(d.status))throw Error(d.error||'فشل النص')}throw Error('انتهت مدة الانتظار. افتح المشاريع لاحقًا.')}
async function productCampaign(){if(!spend(5))return;modal(`<h2>حملة منتج</h2><p>ارفع صورة المنتج. سيحلل Rio الصورة ويقترح حملة كاملة: فكرة، جمهور، زوايا إعلانية، نصوص، CTA وأفكار مرئية.</p><input id="productFile" type="file" accept="image/*"><textarea id="productGoal" class="prompt" placeholder="مثال: أريد حملة لمنتج قهوة تستهدف الشباب في السعودية"></textarea><button class="modal-action" id="productGo">تحليل وبناء الحملة</button><div id="productOut"></div>`);$('#productGo').onclick=async()=>{const f=$('#productFile').files[0];const goal=$('#productGoal').value.trim()||'ابنِ حملة تسويقية شاملة للمنتج الظاهر في الصورة';if(!f)return toast('اختر صورة المنتج');if(f.size>4*1024*1024)return toast('الصورة أكبر من 4MB');const out=$('#productOut');out.textContent='جاري تحليل المنتج وبناء الحملة…';try{const imageData=await dataURL(f);const r=await fetch(API('/api/ai'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'vision',imageData,prompt:`${goal}\nأخرج النتيجة بالعربية في أقسام واضحة: وصف المنتج، الجمهور، الفكرة الكبرى، 3 زوايا إعلانية، 3 نصوص قصيرة، CTA، ألوان/أسلوب بصري، وأفكار فيديو قصيرة.`})});const d=await r.json();if(!r.ok)throw Error(d.error||'فشل التحليل');const text=await pollText(d);out.innerHTML=`<div class="result-card"><div class="result-text">${esc(text)}</div><button class="white-btn" id="copyCampaign">نسخ الحملة</button></div>`;$('#copyCampaign').onclick=()=>navigator.clipboard?.writeText(text).then(()=>toast('تم النسخ'))}catch(e){out.textContent=e.message}}}
async function search(){modal(`<h2>بحث في المشاريع</h2><input id="searchInput" class="prompt" style="min-height:52px" placeholder="اسم المشروع أو نوعه"><button class="modal-action" id="searchGo">بحث</button>`);$('#searchGo').onclick=()=>{const q=$('#searchInput').value.toLowerCase().trim();const rows=projects.filter(p=>(p.name+' '+(p.meta||'')).toLowerCase().includes(q));$('#projectList').innerHTML=rows.map(p=>`<button class="project-row" data-project="${p.id}"><div class="mini">${esc(p.tag||'RIO')}</div><div><b>${esc(p.name)}</b><small>${esc(p.meta||'')}</small></div><span>›</span></button>`).join('')||'<div class="project-row">لا توجد نتائج.</div>';closeModal();showScreen('projects')}}
function templateSearch(){modal(`<h2>بحث القوالب</h2><input id="templateSearch" class="prompt" style="min-height:52px" placeholder="مثال: سفر"><button class="modal-action" id="templateGo">بحث</button>`);$('#templateGo').onclick=()=>{const q=$('#templateSearch').value.toLowerCase();$('#templatesGrid').innerHTML=templates.filter(t=>(t[0]+' '+t[1]).toLowerCase().includes(q)).map(t=>`<button class="template" data-template="${esc(t[0])}"><div class="thumb">${t[2]}</div><b>${esc(t[0])}</b><small>قالب · ${t[3]}</small></button>`).join('');closeModal();showScreen('templates')}}
async function openProject(id){const p=projects.find(x=>x.id===id);if(!p)return;if(p.remoteUrl){if(p.remoteType==='image')return showResult(p.name,`<img src="${esc(p.remoteUrl)}" alt=""><a class="white-btn" href="${esc(p.remoteUrl)}" target="_blank">فتح</a>`);if(p.remoteType==='video')return showResult(p.name,`<video src="${esc(p.remoteUrl)}" controls playsinline></video><a class="white-btn" href="${esc(p.remoteUrl)}" target="_blank">فتح</a>`);if(p.remoteType==='audio')return showResult(p.name,`<audio src="${esc(p.remoteUrl)}" controls></audio><a class="white-btn" href="${esc(p.remoteUrl)}" target="_blank">فتح</a>`)}openEditor();state.projectId=id;$('#editorTitle').textContent=p.name;state.text=p.text||'';state.filter=p.filter||'none';state.ratio=p.ratio||'9/16';applyVisuals()}
function initEditor(){panel('media');if(!state.projectId){$('#editorTitle').textContent='مشروع جديد';state.media=null;state.mediaUrl=null;state.mediaType=null;state.text='';state.filter='none';state.ratio='9/16';$('#video').style.display='none';$('#image').style.display='none';$('#preview').style.display='grid';$('#playBtn').style.display='none';$('#textOverlay').style.display='none';renderTimeline()}}
function setMedia(f){state.history.push({text:state.text,filter:state.filter,ratio:state.ratio});state.media=f;state.mediaUrl=URL.createObjectURL(f);state.mediaType=f.type.startsWith('video')?'video':'image';$('#mediaName').textContent=f.name;$('#preview').style.display='none';$('#video').style.display=state.mediaType==='video'?'block':'none';$('#image').style.display=state.mediaType==='image'?'block':'none';$('#playBtn').style.display=state.mediaType==='video'?'block':'none';if(state.mediaType==='video'){$('#video').src=state.mediaUrl;$('#video').load()}else{$('#image').src=state.mediaUrl}applyVisuals();renderTimeline();toast('تم استيراد الملف فعليًا')}
function renderTimeline(){$('#timeline').innerHTML=(state.media?`<div class="timeline-clip">🎞 ${esc(state.media.name)}</div>`:'')+(state.audio?`<div class="timeline-clip">♫ ${esc(state.audio.name)}</div>`:'')||'<span style="color:#777;font-size:10px">لا توجد وسائط بعد</span>'}
function applyVisuals(){const f=state.filter==='warm'?'sepia(.25) saturate(1.25)':state.filter==='mono'?'grayscale(1)':state.filter==='cinema'?'contrast(1.12) saturate(.85)':'none';$('#video').style.filter=f;$('#image').style.filter=f;$('#textOverlay').textContent=state.text;$('#textOverlay').style.display=state.text?'block':'none';$('#previewWrap').style.aspectRatio=state.ratio}
function addText(t){state.history.push({text:state.text,filter:state.filter,ratio:state.ratio});state.text=t;applyVisuals();toast('تمت إضافة النص')}
function applyFilter(f){state.history.push({text:state.text,filter:state.filter,ratio:state.ratio});state.filter=f;applyVisuals();panel('filter');toast('تم تطبيق الفلتر')}
function setRatio(r){state.history.push({text:state.text,filter:state.filter,ratio:state.ratio});state.ratio=r;applyVisuals();panel('ratio');toast('تم تغيير المقاس')}
function panel(type){const html={
media:`<div class="panel-title">الوسائط</div><div class="tool-buttons"><button class="tool-choice" onclick="$('#mediaInput').click()">＋ فيديو / صورة</button><button class="tool-choice" onclick="$('#audioInput').click()">♫ إضافة صوت</button><button class="tool-choice" onclick="saveCurrentProject()">💾 حفظ</button><button class="tool-choice" onclick="openEditor();aiModal('image')">▧ صورة AI</button></div>`,
text:`<div class="panel-title">النص</div><input id="textInput" class="prompt" style="min-height:52px" placeholder="النص الظاهر على الفيديو" value="${esc(state.text)}"><div class="tool-buttons" style="margin-top:10px"><button class="tool-choice" onclick="addText($('#textInput').value.trim()||'عنوان جديد')">إضافة نص</button><button class="tool-choice" onclick="addText('إعلانك هنا')">عنوان إعلان</button></div>`,
filter:`<div class="panel-title">الفلاتر</div><div class="tool-buttons"><button class="tool-choice ${state.filter==='none'?'active':''}" onclick="applyFilter('none')">أصلي</button><button class="tool-choice ${state.filter==='warm'?'active':''}" onclick="applyFilter('warm')">دافئ</button><button class="tool-choice ${state.filter==='mono'?'active':''}" onclick="applyFilter('mono')">أبيض وأسود</button><button class="tool-choice ${state.filter==='cinema'?'active':''}" onclick="applyFilter('cinema')">سينمائي</button></div>`,
ratio:`<div class="panel-title">المقاس</div><div class="tool-buttons"><button class="tool-choice ${state.ratio==='9/16'?'active':''}" onclick="setRatio('9/16')">9:16</button><button class="tool-choice ${state.ratio==='16/9'?'active':''}" onclick="setRatio('16/9')">16:9</button><button class="tool-choice ${state.ratio==='1/1'?'active':''}" onclick="setRatio('1/1')">1:1</button></div>`,
audio:`<div class="panel-title">الصوت</div><div class="tool-buttons"><button class="tool-choice" onclick="$('#audioInput').click()">＋ إضافة صوت</button><button class="tool-choice" onclick="aiModal('tts')">🎙 تعليق صوتي AI</button><button class="tool-choice" onclick="toggleVideoMute()">🔇 كتم الفيديو</button></div><div id="audioInfo" style="color:#777;margin-top:12px;font-size:10px">${state.audio?esc(state.audio.name):'لا يوجد ملف صوت'}</div>`,
ai:`<div class="panel-title">AI داخل المحرر</div><div class="tool-buttons"><button class="tool-choice" onclick="aiModal('image')">▧ إنشاء صورة</button><button class="tool-choice" onclick="aiModal('image-video')">◉ صورة → فيديو</button><button class="tool-choice" onclick="aiModal('text-video')">✦ نص → فيديو</button><button class="tool-choice" onclick="writer()">✎ كتابة AI</button></div>`}[type]||'';$('#toolPanel').innerHTML=html}
function toggleVideoMute(){const v=$('#video');v.muted=!v.muted;toast(v.muted?'تم كتم الفيديو':'تم تشغيل صوت الفيديو')}
async function saveCurrentProject(){let p=projects.find(x=>x.id===state.projectId);if(!p){p=await newProject($('#editorTitle').textContent||'مشروع ريو','تحرير · '+state.ratio,'EDIT');state.projectId=p.id;projects.unshift(p)}p.name=$('#editorTitle').textContent||p.name;p.text=state.text;p.filter=state.filter;p.ratio=state.ratio;if(state.media){p.fileId='media-'+p.id;p.fileName=state.media.name;await putFile(p.fileId,state.media)}if(state.audio){p.audioId='audio-'+p.id;p.audioName=state.audio.name;await putFile(p.audioId,state.audio)}saveMeta();renderProjects();toast('تم حفظ المشروع محليًا ✓')}
async function exportProject(){if(!state.media)return toast('استورد صورة أو فيديو أولاً');if(state.mediaType==='image')return exportCanvasImage();const v=$('#video');if(!v.duration)return toast('انتظر تحميل الفيديو');const w=state.ratio==='16/9'?1280:state.ratio==='1/1'?1080:720,h=state.ratio==='16/9'?720:state.ratio==='1/1'?1080:1280;const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');const stream=c.captureStream(30);const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm';const rec=new MediaRecorder(stream,{mimeType:mime});const chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{const b=new Blob(chunks,{type:'video/webm'});downloadBlob(b,'rio-export.webm');toast('تم تصدير الفيديو فعليًا ✓')};v.currentTime=0;await v.play().catch(()=>{});rec.start();const duration=Math.min(v.duration,60);const start=performance.now();const draw=()=>{if((performance.now()-start)/1000>=duration){rec.stop();v.pause();return}ctx.filter=state.filter==='warm'?'sepia(.25) saturate(1.25)':state.filter==='mono'?'grayscale(1)':state.filter==='cinema'?'contrast(1.12) saturate(.85)':'none';ctx.drawImage(v,0,0,w,h);ctx.filter='none';if(state.text){ctx.fillStyle='#fff';ctx.font=`bold ${Math.max(34,w/18)}px sans-serif`;ctx.textAlign='center';ctx.shadowColor='#000';ctx.shadowBlur=10;ctx.fillText(state.text,w/2,h*.78)}requestAnimationFrame(draw)};draw()}
async function exportCanvasImage(){const im=$('#image');if(!im.naturalWidth)return toast('انتظر تحميل الصورة');const w=state.ratio==='16/9'?1280:1080,h=state.ratio==='16/9'?720:state.ratio==='1/1'?1080:1280;const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.filter=state.filter==='warm'?'sepia(.25) saturate(1.25)':state.filter==='mono'?'grayscale(1)':state.filter==='cinema'?'contrast(1.12) saturate(.85)':'none';ctx.drawImage(im,0,0,w,h);ctx.filter='none';if(state.text){ctx.fillStyle='#fff';ctx.font=`bold ${Math.max(34,w/18)}px sans-serif`;ctx.textAlign='center';ctx.fillText(state.text,w/2,h*.78)}c.toBlob(b=>{downloadBlob(b,'rio-image-export.png');toast('تم تصدير الصورة ✓')},'image/png')}
function downloadBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)}
async function parseMaterial(file){material.file=file;$('#materialName').textContent=file.name;$('#materialText').textContent='جاري قراءة المادة…';try{if(file.type==='text/plain'||/\.(txt|md|csv)$/i.test(file.name)){material.text=await file.text()}else if(/\.docx$/i.test(file.name)){if(!window.mammoth)throw Error('مكتبة Word لم تُحمّل');const r=await window.mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()});material.text=r.value}else if(/\.pdf$/i.test(file.name)){if(!window.pdfjsLib)throw Error('مكتبة PDF لم تُحمّل');const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;let out='';for(let i=1;i<=Math.min(pdf.numPages,30);i++){const page=await pdf.getPage(i);const c=await page.getTextContent();out+=c.items.map(x=>x.str).join(' ')+'\n'}material.text=out}else throw Error('نوع الملف غير مدعوم');$('#materialText').textContent=material.text.slice(0,30000)||'لم يتم استخراج نص من الملف.'}catch(e){material.text='';$('#materialText').textContent=e.message}}
async function materialAI(kind){if(!material.text)return toast('ارفع مادة تحتوي على نص أولاً');if(!spend(2))return;const prompts={summary:'لخص المادة بالعربية في نقاط واضحة مع أهم الأفكار.',concepts:'استخرج المفاهيم والمصطلحات المهمة واشرح كل مفهوم باختصار.',quiz:'أنشئ اختبارًا من 10 أسئلة متنوعة مع الإجابات في النهاية.',exam:'أنشئ اختبارًا شاملًا من 20 سؤالًا يغطي المادة مع نموذج إجابة.'};const out=$('#materialResult');out.textContent='جاري التحليل…';try{const r=await fetch(API('/api/ai'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'text',prompt:`${prompts[kind]}\n\nالمادة:\n${material.text.slice(0,24000)}`})});const d=await r.json();if(!r.ok)throw Error(d.error||'فشل إرسال المادة');const text=await pollText(d);out.textContent=text}catch(e){out.textContent=e.message}}

document.addEventListener('click',async e=>{
 const nav=e.target.closest('[data-screen]');if(nav){if(nav.dataset.screen==='home'||nav.dataset.screen==='create'||nav.dataset.screen==='templates'||nav.dataset.screen==='materials'||nav.dataset.screen==='projects'||nav.dataset.screen==='account'){closeEditor();showScreen(nav.dataset.screen)}return}
 const pr=e.target.closest('[data-project]');if(pr){await openProject(pr.dataset.project);return}
 const tp=e.target.closest('[data-template]');if(tp){const t=templates.find(x=>x[0]===tp.dataset.template);const p=await newProject(t[0],'قالب قابل للتعديل · '+t[3],t[2]);p.ratio=t[3];projects.unshift(p);saveMeta();renderProjects();state.projectId=p.id;openEditor();toast('تم إنشاء المشروع من القالب');return}
 const a=e.target.closest('[data-action]');if(a){const x=a.dataset.action;if(x==='editor')openEditor();else if(x==='ai-video')aiModal('text-video');else if(x==='ai-image')aiModal('image');else if(x==='image-video')aiModal('image-video');else if(x==='tts')aiModal('tts');else if(x==='stt')aiModal('stt');else if(x==='writer')writer();else if(x==='translate')translate();else if(x==='product')productCampaign();else if(x==='plans')plans();else if(x==='credits')toast('الرصيد التجريبي 120 AI. الدفع الحقيقي سيُضاف عند ربط مزود الدفع.');else if(x==='settings')settings();else if(x==='help')help();else if(x==='search')search();else if(x==='template-search')templateSearch();return}
 const mat=e.target.closest('[data-material-action]');if(mat){materialAI(mat.dataset.materialAction);return}
 const tool=e.target.closest('[data-tool]');if(tool){$$('.tool').forEach(x=>x.classList.remove('active'));tool.classList.add('active');panel(tool.dataset.tool);return}
 const chip=e.target.closest('[data-cat]');if(chip){$$('.chip').forEach(x=>x.classList.remove('active'));chip.classList.add('active');renderTemplates(chip.dataset.cat);return}
});
$('#closeModal').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});$('#importBtn').onclick=()=>$('#mediaInput').click();$('#mediaInput').onchange=e=>{const f=e.target.files[0];if(f)setMedia(f)};$('#audioInput').onchange=e=>{const f=e.target.files[0];if(!f)return;state.audio=f;state.audioUrl=URL.createObjectURL(f);renderTimeline();toast('تمت إضافة الصوت فعليًا')};$('#playBtn').onclick=()=>{const v=$('#video');if(v.paused){v.play();$('#playBtn').textContent='❚❚'}else{v.pause();$('#playBtn').textContent='▶'}};$('#video').ontimeupdate=()=>{if($('#video').duration){$('#seek').value=$('#video').currentTime/$('#video').duration*100;$('#timeLabel').textContent=`${fmt($('#video').currentTime)} / ${fmt($('#video').duration)}`}};$('#seek').oninput=()=>{if($('#video').duration)$('#video').currentTime=$('#video').duration*$('#seek').value/100};$('#saveBtn').onclick=saveCurrentProject;$('#exportBtn').onclick=exportProject;$('#undoBtn').onclick=()=>{const h=state.history.pop();if(!h)return toast('لا توجد عملية للتراجع');state.text=h.text;state.filter=h.filter;state.ratio=h.ratio;applyVisuals();toast('تم التراجع')};$('#materialPick').onclick=()=>$('#materialInput').click();$('#materialInput').onchange=e=>{const f=e.target.files[0];if(f)parseMaterial(f)};
function fmt(s){return String(Math.floor((s||0)/60)).padStart(2,'0')+':'+String(Math.floor((s||0)%60)).padStart(2,'0')}
function init(){saveMeta();renderProjects();renderTemplates();panel('media')}
init();
