const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const templates=[
{name:'فلوق المدينة',cat:'trend',meta:'Preset · 9:16',cls:'t1',tag:'CITY',filter:'cinema',ratio:'9/16',text:'يوم جديد'},
{name:'إعلان منتج',cat:'business',meta:'Preset · 9:16',cls:'t2',tag:'PRODUCT',filter:'warm',ratio:'9/16',text:'اكتشف المنتج'},
{name:'مغامرة وسفر',cat:'travel',meta:'Preset · 16:9',cls:'t3',tag:'TRAVEL',filter:'none',ratio:'16/9',text:'رحلة لا تُنسى'},
{name:'مطاعم ومأكولات',cat:'food',meta:'Preset · 1:1',cls:'t4',tag:'FOOD',filter:'warm',ratio:'1/1',text:'جرب اليوم'},
{name:'مقطع رياضي',cat:'trend',meta:'Preset · 9:16',cls:'t5',tag:'SPORT',filter:'cinema',ratio:'9/16',text:'جاهز للتحدي'},
{name:'قصة قصيرة',cat:'trend',meta:'Preset · 9:16',cls:'t6',tag:'STORY',filter:'mono',ratio:'9/16',text:'قصتك تبدأ هنا'}];
let projects=JSON.parse(localStorage.getItem('rioProjects')||'[]');
let state={media:null,audio:null,mediaType:null,mediaUrl:null,audioUrl:null,filter:'none',ratio:'9/16',text:'',projectId:null,history:[]};
const DB='rioStudioDB', STORE='files';
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2200)}
function saveMeta(){localStorage.setItem('rioProjects',JSON.stringify(projects))}
function showScreen(n){$$('.screen').forEach(x=>x.classList.remove('active'));if(n==='editor'){$('#editor').classList.add('active');$('.bottom-nav').style.display='none';return}$('#'+n)?.classList.add('active');$('.bottom-nav').style.display='flex';$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.screen===n));window.scrollTo(0,0)}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function putFile(id,blob){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(blob,id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function getFile(id){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function delFile(id){try{const db=await openDB();db.transaction(STORE,'readwrite').objectStore(STORE).delete(id)}catch{}}
function renderProjects(){
 $('#recentProjects').innerHTML=projects.slice(0,6).map(p=>`<button class="project-card" data-project="${p.id}"><div class="project-thumb">${p.tag||'RIO'}</div><b>${esc(p.name)}</b><small>${esc(p.meta||'مشروع')}</small></button>`).join('')||'<div style="color:#777;font-size:11px">لا توجد مشاريع بعد.</div>';
 $('#projectList').innerHTML=projects.map(p=>`<button class="project-row" data-project="${p.id}"><div class="mini">${p.tag||'RIO'}</div><div><b>${esc(p.name)}</b><small>${esc(p.meta||'مشروع')}</small></div><span>›</span></button>`).join('')||'<div style="color:#777;font-size:11px">ابدأ بإنشاء أول مشروع.</div>';
}
function renderTemplates(cat='all'){ $('#templateGrid').innerHTML=templates.filter(t=>cat==='all'||t.cat===cat).map(t=>`<button class="template" data-template="${t.name}"><div class="thumb ${t.cls}">${t.tag}</div><b>${t.name}</b><small>${t.meta}</small></button>`).join('') }
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function modal(h){$('#modalBody').innerHTML=h;$('#modal').classList.remove('hidden')}
function plans(){modal(`<h2>خطط ريو</h2><p style="color:#888;font-size:11px">الأسعار واجهة فقط في V0.5؛ لا يوجد خصم مالي فعلي حتى نربط مزود دفع.</p><div class="plans">${[['Starter','19','500'],['Creator','49','2000'],['Pro','99','5000'],['Studio','249','15000']].map((x,i)=>`<div class="plan ${i===1?'featured':''}"><div class="plan-head"><b>${x[0]}</b><strong>${x[1]} ر.س / شهر</strong></div><p>${x[2]} نقطة AI · أدوات التحرير · مشاريع</p></div>`).join('')}</div><button class="modal-action" onclick="toast('الدفع غير مربوط بعد؛ لن يتم خصم أي مبلغ')">اختيار الخطة</button>`) }
function aiModal(type){
 const isImg=type==='image', isI2V=type==='image-video', isTts=type==='tts', title=isImg?'صورة AI':isI2V?'صورة إلى فيديو':isTts?'تعليق صوتي AI':'فيديو AI';
 if(isImg)return modal(`<h2>${title}</h2><textarea id="aiPrompt" class="prompt" placeholder="اكتب وصف الصورة بالتفصيل..."></textarea><div class="field"><label>المقاس</label><div class="selects"><button class="select active" data-choice="ratio" data-value="9:16">9:16</button><button class="select" data-choice="ratio" data-value="1:1">1:1</button><button class="select" data-choice="ratio" data-value="16:9">16:9</button></div></div><button class="modal-action" id="aiSubmit">إنشاء الصورة</button><div id="aiStatus"></div>`),bindChoice(),$('#aiSubmit').onclick=()=>runAI('image');
 if(isTts)return modal(`<h2>${title}</h2><textarea id="ttsText" class="prompt" placeholder="اكتب النص الذي تريد تحويله إلى صوت..."></textarea><div class="field"><label>اللغة</label><div class="selects"><button class="select active" data-choice="lang" data-value="ar">العربية</button><button class="select" data-choice="lang" data-value="en">English</button></div></div><button class="modal-action" id="aiSubmit">إنشاء الصوت</button><div id="aiStatus"></div>`),bindChoice(),$('#aiSubmit').onclick=()=>runAI('tts');
 let extra=isI2V?`<button class="tool-choice" id="pickI2V">اختيار صورة</button><input id="i2vInput" type="file" accept="image/*" hidden>`:'';
 modal(`<h2>${title}</h2>${extra}<textarea id="aiPrompt" class="prompt" placeholder="اكتب ماذا تريد أن يحدث..."></textarea><div class="field"><label>المقاس</label><div class="selects"><button class="select active" data-choice="ratio" data-value="9:16">9:16</button><button class="select" data-choice="ratio" data-value="16:9">16:9</button></div></div><div class="field"><label>الجودة</label><div class="selects"><button class="select active" data-choice="res" data-value="720p">720p</button><button class="select" data-choice="res" data-value="1080p">1080p</button></div></div><button class="modal-action" id="aiSubmit">${isI2V?'إنشاء الفيديو من الصورة':'إنشاء الفيديو الحقيقي'}</button><div id="aiStatus"></div>`);
 bindChoice();if(isI2V){$('#pickI2V').onclick=()=>$('#i2vInput').click();$('#i2vInput').onchange=e=>{state.i2vFile=e.target.files[0];$('#pickI2V').textContent=state.i2vFile?'تم اختيار الصورة ✓':'اختيار صورة'}}$('#aiSubmit').onclick=()=>runAI(isI2V?'image-video':'text-video')
}
function bindChoice(){$$('[data-choice]').forEach(b=>b.onclick=()=>{const k=b.dataset.choice;$$(`[data-choice="${k}"]`).forEach(x=>x.classList.remove('active'));b.classList.add('active')})}
function dataURL(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(blob)})}
async function runAI(type){
 const btn=$('#aiSubmit'), status=$('#aiStatus');btn.disabled=true;status.textContent='جاري إرسال الطلب…';
 try{
  const body={type};
  if(type==='tts'){body.text=$('#ttsText').value.trim();body.languageCode=$('[data-choice="lang"].active')?.dataset.value||'ar'}
  else {body.prompt=$('#aiPrompt').value.trim();body.aspectRatio=$('[data-choice="ratio"].active')?.dataset.value||'9:16';body.resolution=$('[data-choice="res"].active')?.dataset.value||'720p';body.duration='8s';body.generateAudio=true;if(type==='image-video'){if(!state.i2vFile)throw Error('اختر صورة أولاً');body.imageData=await dataURL(state.i2vFile)}}
  if(!body.prompt&&!['tts'].includes(type))throw Error('اكتب الوصف أولاً');if(type==='tts'&&!body.text)throw Error('اكتب النص أولاً');
  const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'فشل الطلب');status.textContent='تم الإرسال. ننتظر النتيجة…';await poll(d,body.prompt||body.text); 
 }catch(e){btn.disabled=false;status.textContent=e.message}
}
async function poll(job,label){for(let i=0;i<120;i++){await new Promise(r=>setTimeout(r,3000));const r=await fetch(`/api/status?requestId=${encodeURIComponent(job.requestId)}&model=${encodeURIComponent(job.model)}&type=${encodeURIComponent(job.type)}`);const d=await r.json();if(!r.ok)throw Error(d.error||'تعذر فحص الحالة');if(d.status==='COMPLETED'){await aiDone(job.type,d,label);return}if(['FAILED','ERROR','CANCELLED'].includes(d.status))throw Error(d.error||'فشل محرك الذكاء الاصطناعي');$('#aiStatus').textContent=d.status==='IN_PROGRESS'?'قيد التوليد…':'في قائمة الانتظار…'}throw Error('التوليد ما زال قيد المعالجة. يمكنك العودة للمشاريع لاحقاً.')}
async function aiDone(type,d,label){
 $('#modal').classList.add('hidden');
 if(type==='image'){const p=await newProject('صورة AI','FLUX · صورة','AI');p.remoteUrl=d.imageUrl;saveMeta();renderProjects();openRemoteImage(p);toast('تم إنشاء الصورة فعليًا ✓')}
 else if(type==='image-video'||type==='text-video'){const p=await newProject(type==='image-video'?'صورة إلى فيديو':'فيديو AI','Veo 3.1 · فيديو','AI');p.remoteUrl=d.videoUrl;saveMeta();renderProjects();openRemoteVideo(p);toast('تم إنشاء الفيديو فعليًا ✓')}
 else if(type==='tts'){const p=await newProject('تعليق صوتي','ElevenLabs · صوت','VOICE');p.remoteUrl=d.audioUrl;saveMeta();renderProjects();openRemoteAudio(p);toast('تم إنشاء الصوت فعليًا ✓')}
 else if(type==='stt'){modal(`<h2>النص المستخرج</h2><textarea class="prompt" style="height:220px">${esc(d.text)}</textarea><button class="modal-action" onclick="navigator.clipboard?.writeText(document.querySelector('.prompt').value);toast('تم النسخ')">نسخ النص</button>`)}
}
async function newProject(name,meta,tag){const p={id:crypto.randomUUID(),name,meta,tag,created:Date.now()};projects.unshift(p);return p}
function initEditor(p){showScreen('editor');state.projectId=p?.id||null;$('#editorTitle').textContent=p?.name||'مشروع جديد';panel('media')}
function clearMedia(){if(state.mediaUrl?.startsWith('blob:'))URL.revokeObjectURL(state.mediaUrl);if(state.audioUrl?.startsWith('blob:'))URL.revokeObjectURL(state.audioUrl);state.media=state.audio=null;state.mediaUrl=state.audioUrl=null}
function setMedia(file){clearMedia();state.media=file;state.mediaType=file.type.startsWith('video')?'video':'image';state.mediaUrl=URL.createObjectURL(file);$('#mediaName').textContent=file.name;$('.empty-preview').style.display='none';$('#video').style.display=state.mediaType==='video'?'block':'none';$('#image').style.display=state.mediaType==='image'?'block':'none';$('#audio').style.display='none';$('#playBtn').style.display=state.mediaType==='video'?'block':'none';if(state.mediaType==='video'){$('#video').src=state.mediaUrl;$('#video').load()}else $('#image').src=state.mediaUrl;renderTimeline();toast('تم استيراد الملف فعليًا')}
async function openProject(id){const p=projects.find(x=>x.id===id);if(!p)return;initEditor(p);if(p.remoteUrl){p.remoteUrl.includes('.mp4')?openRemoteVideo(p):p.remoteUrl.match(/\.(mp3|wav|m4a)/i)?openRemoteAudio(p):openRemoteImage(p);return}if(p.fileId){const b=await getFile(p.fileId);if(b)setMedia(new File([b],p.fileName,{type:p.fileType}))}state.text=p.text||'';state.filter=p.filter||'none';state.ratio=p.ratio||'9/16';applyVisuals()}
function openRemoteVideo(p){initEditor(p);$('.empty-preview').style.display='none';$('#video').style.display='block';$('#image').style.display='none';$('#audio').style.display='none';$('#playBtn').style.display='block';$('#video').src=p.remoteUrl;$('#video').load();$('#mediaName').textContent='فيديو AI';renderTimeline()}
function openRemoteImage(p){initEditor(p);$('.empty-preview').style.display='none';$('#video').style.display='none';$('#image').style.display='block';$('#audio').style.display='none';$('#playBtn').style.display='none';$('#image').src=p.remoteUrl;$('#mediaName').textContent='صورة AI';renderTimeline()}
function openRemoteAudio(p){initEditor(p);$('.empty-preview').style.display='none';$('#video').style.display='none';$('#image').style.display='none';$('#audio').style.display='block';$('#audio').src=p.remoteUrl;$('#mediaName').textContent='صوت AI';renderTimeline()}
function renderTimeline(){$('#timeline').innerHTML=`<div class="timeline-track"><div class="timeline-clip">${state.mediaType==='image'?'الصورة':'الفيديو'}</div>${state.text?'<div class="timeline-clip">النص</div>':''}${state.audio||$('#audio').src?'<div class="timeline-clip">الصوت</div>':''}</div>`}
function addText(text){state.history.push({text:state.text,filter:state.filter,ratio:state.ratio});state.text=text;$('#textOverlay').textContent=text;$('#textOverlay').style.display='block';renderTimeline();toast('النص مضاف فعليًا إلى المعاينة')}
function applyFilter(f,el){state.history.push({text:state.text,filter:state.filter,ratio:state.ratio});state.filter=f;applyVisuals();if(el){$$('.tool-choice').forEach(x=>x.classList.remove('active'));el.classList.add('active')}toast('تم تطبيق الفلتر')}
function setRatio(r,el){state.history.push({text:state.text,filter:state.filter,ratio:state.ratio});state.ratio=r;$('#previewWrap').style.aspectRatio=r.replace('/','/');if(el){$$('.tool-choice').forEach(x=>x.classList.remove('active'));el.classList.add('active')}toast('تم تغيير المقاس')}
function applyVisuals(){const p=state.filter==='warm'?'sepia(.25) saturate(1.25)':state.filter==='mono'?'grayscale(1)':state.filter==='cinema'?'contrast(1.12) saturate(.85)':'none';$('#video').style.filter=p;$('#image').style.filter=p;$('#textOverlay').textContent=state.text;$('#textOverlay').style.display=state.text?'block':'none';$('#previewWrap').style.aspectRatio=state.ratio}
function panel(type){const p={media:`<div class="panel-title">الوسائط</div><div class="tool-buttons"><button class="tool-choice" onclick="$('#mediaInput').click()">＋ فيديو/صورة</button><button class="tool-choice" onclick="$('#audioInput').click()">♫ صوت</button><button class="tool-choice" onclick="saveCurrentProject()">💾 حفظ</button>`,text:`<div class="panel-title">النص</div><div class="field"><input id="textInput" class="prompt" style="height:48px" placeholder="اكتب النص على الفيديو" value="${esc(state.text)}"></div><div class="tool-buttons"><button class="tool-choice" onclick="addText($('#textInput').value||'عنوان جديد')">إضافة نص</button><button class="tool-choice" onclick="addText('إعلانك هنا')">إعلان</button>`,filter:`<div class="panel-title">الفلاتر</div><div class="tool-buttons"><button class="tool-choice ${state.filter==='none'?'active':''}" onclick="applyFilter('none',this)">أصلي</button><button class="tool-choice ${state.filter==='warm'?'active':''}" onclick="applyFilter('warm',this)">دافئ</button><button class="tool-choice ${state.filter==='mono'?'active':''}" onclick="applyFilter('mono',this)">أبيض وأسود</button><button class="tool-choice ${state.filter==='cinema'?'active':''}" onclick="applyFilter('cinema',this)">سينمائي</button>`,ratio:`<div class="panel-title">المقاس</div><div class="tool-buttons"><button class="tool-choice ${state.ratio==='9/16'?'active':''}" onclick="setRatio('9/16',this)">9:16</button><button class="tool-choice ${state.ratio==='16/9'?'active':''}" onclick="setRatio('16/9',this)">16:9</button><button class="tool-choice ${state.ratio==='1/1'?'active':''}" onclick="setRatio('1/1',this)">1:1</button>`,audio:`<div class="panel-title">الصوت</div><div class="tool-buttons"><button class="tool-choice" onclick="$('#audioInput').click()">＋ إضافة صوت</button><button class="tool-choice" onclick="aiModal('tts')">🎙 صوت AI</button><button class="tool-choice" onclick="toggleMute()">🔇 كتم/تشغيل</button>`,ai:`<div class="panel-title">أدوات AI</div><div class="tool-buttons"><button class="tool-choice" onclick="aiModal('image')">▧ صورة AI</button><button class="tool-choice" onclick="aiModal('image-video')">◉ صورة → فيديو</button><button class="tool-choice" onclick="aiModal('text-video')">✦ نص → فيديو</button><button class="tool-choice" onclick="transcribeAudio()">Aa تفريغ الصوت</button>`};$('#toolPanel').innerHTML=p[type]||p.media}
function toggleMute(){if($('#video').muted){$('#video').muted=false;toast('تم تشغيل الصوت')}else{$('#video').muted=true;toast('تم كتم الصوت')}}
async function transcribeAudio(){if(!state.audio){toast('أضف ملف صوت أولاً');return}modal('<h2>تفريغ الصوت</h2><p style="color:#888;font-size:11px">يتم إرسال الصوت إلى محرك التفريغ.</p><div id="sttStatus">جاري الإرسال…</div>');try{const data=await dataURL(state.audio);const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'stt',audioData:data})});const d=await r.json();if(!r.ok)throw Error(d.error);await poll(d,'');}catch(e){$('#sttStatus').textContent=e.message}}
async function saveCurrentProject(){const name=($('#editorTitle').textContent||'مشروع ريو').trim();let p=projects.find(x=>x.id===state.projectId);if(!p){p=await newProject(name,'تحرير · '+state.ratio,'EDIT');state.projectId=p.id}p.name=name;p.text=state.text;p.filter=state.filter;p.ratio=state.ratio;if(state.media){p.fileId='media-'+p.id;p.fileName=state.media.name;p.fileType=state.media.type;await putFile(p.fileId,state.media)}if(state.audio){p.audioId='audio-'+p.id;await putFile(p.audioId,state.audio)}saveMeta();renderProjects();toast('تم حفظ المشروع فعليًا')} 
async function exportProject(){const video=$('#video'),image=$('#image');if(!state.mediaUrl&&!(video.src||image.src))return toast('أضف ملفًا أولاً');const duration=state.mediaType==='image'?5:(isFinite(video.duration)&&video.duration?video.duration:5);const w=state.ratio==='16/9'?1280:state.ratio==='1/1'?1080:720,h=state.ratio==='16/9'?720:state.ratio==='1/1'?1080:1280;const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');const stream=canvas.captureStream(30);if(video.captureStream&&state.mediaType==='video'){try{video.muted=true;video.currentTime=0;const vs=video.captureStream();vs.getAudioTracks().forEach(t=>stream.addTrack(t))}catch{}}const rec=new MediaRecorder(stream,{mimeType:'video/webm'});const chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{const blob=new Blob(chunks,{type:'video/webm'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='rio-export.webm';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);toast('تم تصدير ملف فيديو فعلي ✓')};if(state.mediaType==='video'){video.currentTime=0;await video.play().catch(()=>{})}rec.start();const start=performance.now();function draw(){const elapsed=(performance.now()-start)/1000;if(elapsed>=duration){rec.stop();video.pause();return}ctx.filter=state.filter==='warm'?'sepia(.25) saturate(1.25)':state.filter==='mono'?'grayscale(1)':state.filter==='cinema'?'contrast(1.12) saturate(.85)':'none';if(state.mediaType==='image')ctx.drawImage(image,0,0,w,h);else ctx.drawImage(video,0,0,w,h);ctx.filter='none';if(state.text){ctx.fillStyle='white';ctx.font=`bold ${Math.max(34,w/18)}px sans-serif`;ctx.textAlign='center';ctx.shadowColor='black';ctx.shadowBlur=10;ctx.fillText(state.text,w/2,h*.75)}requestAnimationFrame(draw)}draw()}
$('#importBtn').onclick=()=>$('#mediaInput').click();$('#mediaInput').onchange=e=>{const f=e.target.files[0];if(f)setMedia(f)};$('#audioInput').onchange=e=>{const f=e.target.files[0];if(!f)return;state.audio=f;state.audioUrl=URL.createObjectURL(f);$('#audio').src=state.audioUrl;$('#audio').style.display='block';renderTimeline();toast('تمت إضافة الصوت فعليًا')};$('#playBtn').onclick=()=>{const v=$('#video');if(v.paused){v.play();$('#playBtn').textContent='❚❚'}else{v.pause();$('#playBtn').textContent='▶'}};$('#video').ontimeupdate=()=>{if($('#video').duration){$('#seek').value=$('#video').currentTime/$('#video').duration*100;$('#timeLabel').textContent=`${fmt($('#video').currentTime)} / ${fmt($('#video').duration)}`}};$('#seek').oninput=()=>{if($('#video').duration)$('#video').currentTime=$('#video').duration*$('#seek').value/100};$('#exportBtn').onclick=exportProject;$('#undoBtn').onclick=()=>{const h=state.history.pop();if(!h)return toast('لا توجد عملية للتراجع');state.text=h.text;state.filter=h.filter;state.ratio=h.ratio;applyVisuals();toast('تم التراجع فعليًا')};$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');
$$('.tool').forEach(t=>t.onclick=()=>{$$('.tool').forEach(x=>x.classList.remove('active'));t.classList.add('active');panel(t.dataset.tool)});
$$('.chip').forEach(c=>c.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');renderTemplates(c.dataset.cat)});
document.addEventListener('click',async e=>{const pr=e.target.closest('[data-project]');if(pr){await openProject(pr.dataset.project);return}const nav=e.target.closest('[data-screen]');if(nav){showScreen(nav.dataset.screen);return}const tp=e.target.closest('[data-template]');if(tp){const t=templates.find(x=>x.name===tp.dataset.template);const p=await newProject(t.name,'قالب قابل للتعديل · '+t.ratio,t.tag);p.text=t.text;p.filter=t.filter;p.ratio=t.ratio;saveMeta();renderProjects();await openProject(p.id);applyVisuals();toast('تم تطبيق القالب ويمكنك تعديله');return}const a=e.target.closest('[data-action]');if(!a)return;const x=a.dataset.action;if(x==='create')showScreen('create');else if(x==='editor')initEditor();else if(x==='templates')showScreen('templates');else if(x==='projects')showScreen('projects');else if(x==='account')showScreen('account');else if(x==='plans')plans();else if(x==='ai-video'||x==='text-video')aiModal('text-video');else if(x==='ai-image')aiModal('image');else if(x==='image-video')aiModal('image-video');else if(x==='tts')aiModal('tts');else if(x==='settings')modal('<h2>الإعدادات</h2><div class="settings-list"><button onclick="toast(\'المشروع يعمل على Vercel\')">حالة الاتصال <b>›</b></button><button onclick="localStorage.clear();location.reload()">مسح بيانات المشاريع المحلية <b>›</b></button></div>');else if(x==='help')modal('<h2>مركز المساعدة</h2><p style="color:#888;line-height:1.8;font-size:12px">استورد ملفًا، عدّل النص والفلاتر والمقاس، أضف الصوت، احفظ المشروع ثم صدّره. أدوات AI تستخدم FAL_KEY الموجود على الخادم.</p>');else if(x==='search')modal('<h2>بحث المشاريع</h2><input id="searchInput" class="prompt" style="height:48px" placeholder="اكتب اسم المشروع"><button class="modal-action" onclick="searchProjects()">بحث</button>');else if(x==='template-search')modal('<h2>بحث القوالب</h2><input id="templateSearch" class="prompt" style="height:48px" placeholder="مثال: سفر"><button class="modal-action" onclick="filterTemplatesText()">بحث</button>')});
window.searchProjects=()=>{const q=$('#searchInput').value.trim().toLowerCase();$('#projectList').innerHTML=projects.filter(p=>p.name.toLowerCase().includes(q)).map(p=>`<button class="project-row" data-project="${p.id}"><div class="mini">${p.tag||'RIO'}</div><div><b>${esc(p.name)}</b><small>${esc(p.meta||'مشروع')}</small></div><span>›</span></button>`).join('')||'<div style="color:#777">لا توجد نتائج.</div>';$('#modal').classList.add('hidden');showScreen('projects')};window.filterTemplatesText=()=>{const q=$('#templateSearch').value.trim().toLowerCase();$('#templateGrid').innerHTML=templates.filter(t=>(t.name+' '+t.cat).toLowerCase().includes(q)).map(t=>`<button class="template" data-template="${t.name}"><div class="thumb ${t.cls}">${t.tag}</div><b>${t.name}</b><small>${t.meta}</small></button>`).join('');$('#modal').classList.add('hidden');showScreen('templates')};
function fmt(s){return String(Math.floor((s||0)/60)).padStart(2,'0')+':'+String(Math.floor((s||0)%60)).padStart(2,'0')}
renderProjects();renderTemplates();panel('media');
